import axios from "axios";
import { useEffect, useState } from "react";
import forge, { pki } from "node-forge";

const PrivateKey = "LS0tLS1CRUdJTiBQUklWQVRFIEtFWS0tLS0tCk1JSUV2UUlCQURBTkJna3Foa2lHOXcwQkFRRUZBQVNDQktjd2dnU2pBZ0VBQW9JQkFRRFRDc0pMelBYMU9ZeksKcVdseGxmdThzL0JHb1RpcHAzK0wxcjVVeEt3YXUxS3RMdFlUb0VTeXYvUTBBSmFUVC9OVVpKdFh3NW1JWCs0awp4dkluYng5cFovSlBrckplNVQvMlYreUo1ai80a3lWVXVnbmlvQ0M1UXJvM2w2VWEwZXFBdFlTUDJrSDlTRnFMCnhUM3hHNlVlcWQwdXRmblNDTkp5OUUydStNbFVIcVBNdDdYa3lyaStWeWJkWkJSTDNUMzMxZVNlOEhEdjRjc1QKcENkaVJ5RC9OV1R3Q1hHU2pDNGtuTVJTN2JrV3Q1WVFrKyt2a2JHd0g2ejVnc1dRU0hSd3lXSGRabmY5eVJQawpSemNsVmZvU3IwOXRCaDBKZUUyd2NTMTNtaWd5TDQvbnRLK0ZxODBMb3RKZTZDdW9RSm1PMWZIV0crNTNybXRXCnphT3A0b0JmQWdNQkFBRUNnZ0VBVnliQ1JmdEdOeGFsQmF3Z1Z6L1F6WVNoWFFtSEZNaU82M2lxOE9hbkRBTC8KaVhVbUFzVFVtZHliUkQ1WjhFdTcrTVh6UUxNTjNEdUJaTDZqa1pWYUszVTVvNUs1Qm1jMW1zMkVhUTRrck1wWApTRDNyaHlNSllIZ2wzbjlKTjJJb3JTNUlwLzlCOFE3SUZhQkdqQ01XZFN0QW8rR1NZU0l6aGpWTlAweU9GNll2Ckc1MWR6ZlNNbThBVlF1Q0NRSTUyNXd3ZEVhMnFUWmJuVlNPODIrR0JBYjZFUm5tbW9zRmlyYnRQYklZV2NtSXQKWVlBL1h4enZzK0N1OGh1THBmeTNWVGdobERpTWdzREtOUTkyZ2pYYlI2cjlLK2NTbm5VR0RBbGt4blJsVkJUOQpDQmhudUIxVUhiSWpWSm14Tmh6Tm1HRXFkYzFkbVllRjg5aHNLdTVGQVFLQmdRRFlycmxJM0NvRklBbXY5T01qCndHOEM2Y0hsb2EzeHVySXdabG1vWFJZWVYxdWZzRE5vZHQwZVRkNGlnRmNJOEdqVmNEMHZxVEZDTDFKODNYYkMKTGkwMWora3pPVEdYZUU5bjIyVzFnSW8zSWljbW1HNnpGeXBSb1BlcWdBZFZvQWNqZjJ3UHpmWVdLOVpSSW8xSApIU0JSSHlWU3doR3JjU2JPc05WemtCUXRVUUtCZ1FENVZnWmJyRnhZV3NJa1VsQ2NzSURaNmtHcHpZOXJERSszCjdJWXV6NkdETnVCTURPMlkyQnV0R0RocWdmSC9KYkpEbEtIUEZ2dmd4dkk5b09kOEVQdHBzTlFwWVAxQU4wRm0KZ3hOOS91RnRjLzNJMEFMT25VQ01TRHY3Y0dsUmVCckt1UXpyaVZtN2RpMDBYVXo5WGFwdEEwTlN6Mmdqb2NMZQpUTmU1YWlXbXJ3S0JnUUNSMEJKemkyVGppZ202MU9xOU5sUDkrOXcxY1RXaXcrWUJWLzdobzdLb3NyQy9wMDBRCjhWd2ZkbnNUY0pZaE45YjBPdEdSN3lOc3pIZVArMkJkajhGd2wrVndTUDZzVlpQcDZlUnAzWlFsUWVCaXdwVk0KQXp6QkxiYzhqMmRnSVk1c1B1VXpSWUJpcnlGTC9CcGlUcUZldGJ6aUVpTGQ0Z2toY2pKUjBCVWo0UUtCZ0R1bgptVjNWbjBLRWRHNjhRdzA2TFpuMXNrQXVMbUl1VCtSeGNxbEFoQ1FndlFsMURtUERVTnZaTDZaTDhOcGE2b3ZBCncvWUlTYnM5M2pkZ2lBSG5Eai83VHNlWHJQL3dPSFdPWnR0K1gvRVFEMmc4WEcrU3NCN2dLWG0vSzNPU2lOWjMKNzk5cXZVMWN1UFFPWHAxQUM4YUpRVkpPelZ1NUdDYVh2QVZnb0NHQkFvR0FheDYzZGdLS3pHZ281ZGxGcXk3dgpGL2RPMGxmMGRMTC9HZjhrWU94dmxob3Z6THBCVG5OSHdUdmdTdUcyR1d2VERabFNqTUc0N2lmQnFRN3JMb3J4CmIzYXQ3NjQwMTdJVDNqbzQvVEtDTHdzanU0YTdpUjNVUG1WVnV6T1BCdStLTkQ5RmFici9XTXErRHNoSUN5NFoKcXRQQ0ZpUUxIZVVsZnBoalZuU3F0S0E9Ci0tLS0tRU5EIFBSSVZBVEUgS0VZLS0tLS0K";
const PublicKey = "LS0tLS1CRUdJTiBQVUJMSUMgS0VZLS0tLS0KTUlJQklqQU5CZ2txaGtpRzl3MEJBUUVGQUFPQ0FROEFNSUlCQ2dLQ0FRRUEwd3JDUzh6MTlUbU15cWxwY1pYNwp2TFB3UnFFNHFhZC9pOWErVk1Tc0dydFNyUzdXRTZCRXNyLzBOQUNXazAvelZHU2JWOE9aaUYvdUpNYnlKMjhmCmFXZnlUNUt5WHVVLzlsZnNpZVkvK0pNbFZMb0o0cUFndVVLNk41ZWxHdEhxZ0xXRWo5cEIvVWhhaThVOThSdWwKSHFuZExyWDUwZ2pTY3ZSTnJ2akpWQjZqekxlMTVNcTR2bGNtM1dRVVM5MDk5OVhrbnZCdzcrSExFNlFuWWtjZwovelZrOEFseGtvd3VKSnpFVXUyNUZyZVdFSlB2cjVHeHNCK3MrWUxGa0VoMGNNbGgzV1ozL2NrVDVFYzNKVlg2CkVxOVBiUVlkQ1hoTnNIRXRkNW9vTWkrUDU3U3ZoYXZOQzZMU1h1Z3JxRUNaanRYeDFodnVkNjVyVnMyanFlS0EKWHdJREFRQUIKLS0tLS1FTkQgUFVCTElDIEtFWS0tLS0tCg==";

const PrivateKey01 = "LS0tLS1CRUdJTiBQUklWQVRFIEtFWS0tLS0tCk1JSUVvd0lCQUFLQ0FRRUFtd2lWUWxBSVdseThqSWx2ZlQyVzhPaXJlRjFsalZnUXdEWkxnS0RKTVZLdHluUnMKY2pUR21sVjRxOVRkOHAxbjZwY1ZhWVV1ZEZkSXlVaTdSc1dUcTQxdzdrOWJ0WU5YSFJTUzRYTUY3WWRrb0ZIcgowWkloV1p1R0hVdmZvYVZ1WWpKbVdvZWZzU2R4RDdzTXNOektnOU50S3Z5YjBZaURqV0ZQK2ZBOFROb2NJQnlUCjVQb0pHd2JGMTlmejdDUmswQjVmcVlkRVhWYk8zejA4NDRIaHlIZHQySHJuUXFOdnlxWGgwai85L1grc3FUd0EKVjVFQXRlQXZlS1k0bCszZlVRWU1ObTV4NUtDcHVRQnBiYW4wVG9tU2JUNHB1V2NSNVQ4dnB5QU9iK1Z3MkorbgpjSEtZUkp6cGM4VmJWQkhWYlJZNGtyQTE2WkRJZHd4TUVSNzVzUUlEQVFBQkFvSUJBSEZndllkWmNFSmxQNTZuCmc5bGJpVjkxU0xFbDNIYVp5T1pJenI2cTEzZ3l0dFl3Zm42bkNmY2tPck92WVFGbEMvSUx1NlVIdVFsc0s5YkkKVWUxWDRMNjlHYkd1WjZzKytoNVNSWGlLM2ZMdjZTODF1ZmZ4bm1JaDB0cnArZ29GS2N5MmZ4UUZ5MHVMUkt2MApaenVRdktuYm5TS3F5bWxhSkpyb1o4eXBXKy8zRHVhUjNLa21ZenBZcTdkbFl4L3JvTEx3TXFhOERQZjdJR0YrCmtZVmpNWkduK3NYb0hucTI0YWs4elptMU9STmRSbWNkL1h1aEhzNXllZ0ZndHRpb3BhdWk0UVhlbWU1ait0ODgKWmZDRXpJTCtWeWQ2VGUrODFlbGU0SHVlcC84UXU5bm1pa00xNXFTbFZ6aUEwMWNRT1gwbmFqQXFXVGwyR0VhWgpsZFRSYUlFQ2dZRUF4bklBbDBNYjhjZVU4RFBkb1B1S2J3MlBaV1htMmtPaXkyZVVUZHdCaHR1NEtWeVZUYWNGCkROcjQyT2hsQjhFU0RXV01jRlEyaGh6VEtQZTQ5M0I3OWsrRk5OdXB0NGY3TGtSbGxKOUtjRElDbytSUWk5QjQKanJ5akFaOSszdkpCTXpBUmNlcmhFQVpkclA4R1U0Z09ndnpEOVpoSWN0WDVLYVhiaG5JQTgvVUNnWUVBeC85aApFTE1kVHl2UCt4S0VNK09UUDNwc2w1ckM5citnVUE4YWRBZHUrQ1hwb2YxNzNGYVVjeFo3MExBUmVMQ2ZPUjFLClJCMVhXTGIwbjZ3OXdoREI5QzJ2R0FDUTJwalNqblFZajIySDA3aE81bmh0STZWeDdBZU51aGFCS1MzR0hGdHAKNkkzbWJhYW80NENLSnVmUHlTaW9NbHV0MVVKdHh4WlJwcVo0bFUwQ2dZQkRxMlJnTUZZN0lGKzllVEkrVHdocAp6aW56M2NmVzdmRjVneHlqWUQ1MUNqL0dldmUrdnhHTnpLM0c2WmhxQ0lCcmFSRjJ6SUM3UXVFT3UwcXJ0Z1BQCmZsWmlLL1czeS9ydlVBdURucjMzZkZaQ0pQMENjRmhyOUE5eDRqMlZNTzdpMGFWaFAwTDMvL081cGswMTl0TmIKLzIyak5nYWVnakN3N3dubzByOVljUUtCZ1FDRUorTFNFQ21yNlQyVG9OYXZHeEJ2Lzh2R0drUCtuUDJvS1hMSApmU244MjhDWWhGSFdkWGUrM1BxUUdlaFJvaFIwdjBBVjVuV1RiOElSeU5VK2FhaGdXOWU1dXBYOWZNS1YwMjF2ClNXZFpwZzZ0Q0tMRnpVdU1OaW1XNzh3RmsvTzNSVWlrblMvSkFUblVxMW1lLzhzMEY2T2RNeXVaSWo0OE1pbGUKUDk2cWVRS0JnR0srWW9zdEVTRGxxeGMrL1pzNk0wL1RqZ3N4NTVTU2NEaTFSRGtSMTVxb0pSK01ETUN3c28vZgoxTU5EZng3c080bS9iQXRFVldnb3IvSkF1aGxGU0tQNFpGeWdEZ25HSjcxdkk2anZEdmtQNHBldG9QYXpPei9ZCmJUNnQxRThYZTZJK2FDYm9Yc1dIdlh4dkNoNjlUbGxrSXZkTlU2aVJVVUxoMHYxVFNwaSsKLS0tLS1FTkQgUFJJVkFURSBLRVktLS0tLQo=";
const PublicKey01 = "LS0tLS1CRUdJTiBQVUJMSUMgS0VZLS0tLS0KTUlJQkNnS0NBUUVBbXdpVlFsQUlXbHk4aklsdmZUMlc4T2lyZUYxbGpWZ1F3RFpMZ0tESk1WS3R5blJzY2pURwptbFY0cTlUZDhwMW42cGNWYVlVdWRGZEl5VWk3UnNXVHE0MXc3azlidFlOWEhSU1M0WE1GN1lka29GSHIwWkloCldadUdIVXZmb2FWdVlqSm1Xb2Vmc1NkeEQ3c01zTnpLZzlOdEt2eWIwWWlEaldGUCtmQThUTm9jSUJ5VDVQb0oKR3diRjE5Zno3Q1JrMEI1ZnFZZEVYVmJPM3owODQ0SGh5SGR0MkhyblFxTnZ5cVhoMGovOS9YK3NxVHdBVjVFQQp0ZUF2ZUtZNGwrM2ZVUVlNTm01eDVLQ3B1UUJwYmFuMFRvbVNiVDRwdVdjUjVUOHZweUFPYitWdzJKK25jSEtZClJKenBjOFZiVkJIVmJSWTRrckExNlpESWR3eE1FUjc1c1FJREFRQUIKLS0tLS1FTkQgUFVCTElDIEtFWS0tLS0tCg==";

function SignInPage({ ...props }) {

    const [base64EncodedPublicKey, setBase64EncodedPublicKey] = useState<string>();
    const [userId, setUserId] = useState<string>();
    const [userPwd, setUserPwd] = useState<string>();
    // const mutation = usePostSignUpMutation();
    const post = () => {
        return new Promise<string>((resolve) => resolve(""));
    }
    
    useEffect(() => {
         // 공개키 취득
         // const rsaResponse = axios.get("/v1/rsa");
         const publicKey = pki.publicKeyFromPem(atob(PublicKey01));
        //  const encrypted = publicKey.encrypt("원피스 사실 없다.", "RSAES-PKCS1-V1_5");
         const encrypted = publicKey.encrypt(forge.util.encodeUtf8("원피스 사실 없다."), "RSAES-PKCS1-V1_5");
         const privateKey = pki.privateKeyFromPem(atob(PrivateKey01));
         console.log(btoa(encrypted));
        //  console.log(privateKey.decrypt(encrypted, "RSAES-PKCS1-V1_5"));
        console.log(privateKey.decrypt(encrypted, "RSAES-PKCS1-V1_5"));
        console.log(forge.util.decodeUtf8(privateKey.decrypt(encrypted, "RSAES-PKCS1-V1_5")));
    }, []);

    const handleSubmit = () => {    
        alert('서버 통신');

        // 공개키 인코드

        // API 전송

        // 성공 시 Go Home
    }

    return (
        <>
            <h1>로그인 페이지</h1>
            <span>ID 입력</span>
            <input type="text" onChange={(e) => setUserId(e.target.value)} />
            <span>PWD 입력</span>
            <input type="password" onChange={(e) => setUserPwd(e.target.value)} />
            <button onClick={handleSubmit}>로그인</button>
        </>
    );
}

// export async function getServerSideProps() {
//     const rsaResponse = await axios.get("/v1/rsa");
    
//     return { props: { base64EncodedPublicKeyPem: rsaResponse.data } };
// }

export default SignInPage;